/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    posts: Post;
    categories: Category;
    tags: Tag;
    authors: Author;
    promociones: Promocion;
    plataformas: Plataforma;
    banners: Banner;
    'puntos-de-venta': PuntoDeVenta;
    media: Media;
    users: User;
    redirects: Redirect;
    search: Search;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'media';
    };
  };
  collectionsSelect: {
    posts: PostsSelect<false> | PostsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    promociones: PromocionesSelect<false> | PromocionesSelect<true>;
    plataformas: PlataformasSelect<false> | PlataformasSelect<true>;
    banners: BannersSelect<false> | BannersSelect<true>;
    'puntos-de-venta': PuntosDeVentaSelect<false> | PuntosDeVentaSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | 'es' | 'es'[];
  globals: {
    'payload-jobs-stats': PayloadJobsStat;
  };
  globalsSelect: {
    'payload-jobs-stats': PayloadJobsStatsSelect<false> | PayloadJobsStatsSelect<true>;
  };
  locale: 'es';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      scrapearPromociones: TaskScrapearPromociones;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Guías, tutoriales y notas informativas.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  titulo: string;
  /**
   * Se genera solo si lo dejas vacío. Una vez publicado, cambiarlo pide cargar un 301.
   */
  slug?: string | null;
  /**
   * Se muestra en los listados y sirve de respaldo para la meta descripción si no cargas una.
   */
  resumen: string;
  /**
   * Opcional. Si no cargas una, la entrada se publica igual y en los listados aparece solo con texto.
   */
  portada?: (number | null) | Media;
  /**
   * Escribí directo. Con "/" insertás tablas, avisos, FAQs, imágenes o HTML.
   */
  contenido: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  categoria: number | Category;
  etiquetas?: (number | Tag)[] | null;
  autor: number | Author;
  /**
   * Se completa sola al publicar. Edítala si necesitas otra fecha.
   */
  publicadoEn?: string | null;
  /**
   * Mostrar la fecha de revisión es una señal de contenido mantenido, que pesa en este vertical.
   */
  actualizadoEn?: string | null;
  /**
   * Aparece primero en la portada.
   */
  destacado?: boolean | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Imágenes que usan las entradas, los autores y las portadas. Organizalas en carpetas desde "Explorar por Carpeta".
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Qué se ve en la imagen. Lo leen los lectores de pantalla y lo usa Google: no lo dejes vacío ni repitas el título.
   */
  alt: string;
  epigrafe?: string | null;
  folder?: (number | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: number;
  name: string;
  folder?: (number | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: number | FolderInterface;
        }
      | {
          relationTo?: 'media';
          value: number | Media;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Cada categoría es un silo de contenido con su propia página pilar.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  nombre: string;
  /**
   * Se genera solo si lo dejas vacío. Una vez publicado, cambiarlo pide cargar un 301.
   */
  slug?: string | null;
  /**
   * Texto de la página pilar. Es la que compite por el término genérico, así que conviene que sea sustancial.
   */
  descripcion?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Temas transversales. A diferencia de las categorías, una entrada puede llevar varias.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  nombre: string;
  /**
   * Se genera solo si lo dejas vacío. Una vez publicado, cambiarlo pide cargar un 301.
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Perfiles públicos que firman las entradas.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: number;
  nombre: string;
  /**
   * Se genera solo si lo dejas vacío. Una vez publicado, cambiarlo pide cargar un 301.
   */
  slug?: string | null;
  /**
   * Por ejemplo: "Analista de apuestas deportivas".
   */
  cargo?: string | null;
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  foto?: (number | null) | Media;
  /**
   * Formación, años de experiencia, certificaciones.
   */
  credenciales?:
    | {
        texto: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Perfiles externos que respaldan la identidad del autor.
   */
  enlaces?:
    | {
        etiqueta: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Opcional: vincula este perfil con una cuenta del panel.
   */
  usuario?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * Cuentas con acceso al panel. El perfil público del autor vive en Autores.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  nombre: string;
  /**
   * Autor: crea y edita entradas. Editor: además publica y borra. Administrador: además gestiona usuarios.
   */
  rol: 'admin' | 'editor' | 'autor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Bonos y ofertas de las plataformas. El bot las publica y las expira solo: lo que se edita acá lo pisa la corrida siguiente, salvo el tipo y el resumen.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promociones".
 */
export interface Promocion {
  id: number;
  plataforma: number | Plataforma;
  titulo: string;
  /**
   * Se genera solo si lo dejas vacío. Una vez publicado, cambiarlo pide cargar un 301.
   */
  slug?: string | null;
  tipo: 'bienvenida' | 'recarga' | 'sin-deposito' | 'giros-gratis' | 'cashback' | 'torneo' | 'otro';
  /**
   * El gancho, tal como se muestra: "100% hasta $50.000 + 200 giros".
   */
  oferta?: string | null;
  /**
   * Se muestra en el listado y sirve de meta descripción.
   */
  resumen?: string | null;
  /**
   * Opcional. Si la cargás, se muestra en lugar de la imagen que trae la plataforma.
   */
  portada?: (number | null) | Media;
  /**
   * La que publica la plataforma. La escribe el bot.
   */
  imagenOrigen?: string | null;
  /**
   * Tal como lo publica la plataforma: "30x sobre bono".
   */
  rollover?: string | null;
  depositoMinimo?: string | null;
  /**
   * Cuánto saldo real como máximo puede salir del bono.
   */
  topeDeConversion?: string | null;
  /**
   * La cuota que tiene que tener la apuesta para que cuente al rollover. Solo en los bonos de deportes.
   */
  cuotaMinima?: number | null;
  /**
   * En días, contados desde que se acredita el bono.
   */
  diasParaCumplir?: number | null;
  usosPorUsuario?: number | null;
  /**
   * Vacío es "la plataforma no lo aclara".
   */
  combinable?: ('si' | 'no') | null;
  activacion?: ('automatica' | 'a-pedido') | null;
  /**
   * Vacío si la promoción no pide código.
   */
  codigo?: string | null;
  /**
   * El listado del sitio se puede filtrar por esto. Si cargás la promoción a mano y lo dejás vacío, no va a aparecer con ningún filtro puesto.
   */
  verticales?: ('casino' | 'casino-en-vivo' | 'deportes' | 'esports' | 'virtuales')[] | null;
  /**
   * Solo si la promoción limita a una lista. Vacío es "no la limita".
   */
  juegosHabilitados?: number | null;
  /**
   * Un punto por línea. Los trae el bot del resumen que publica la plataforma en las bases del bono.
   */
  puntosClave?: string | null;
  /**
   * Adónde manda el botón. Absoluta, no relativa.
   */
  urlDestino: string;
  vigenciaDesde?: string | null;
  /**
   * Vacío es "sin fecha de corte publicada", no "para siempre".
   */
  vigenciaHasta?: string | null;
  /**
   * Cuando una promoción desaparece de la plataforma, el bot la marca expirada en vez de borrarla: así la URL sigue existiendo y no se pierde lo indexado.
   */
  estado: 'activa' | 'expirada';
  /**
   * Aparece primero en el listado.
   */
  destacada?: boolean | null;
  /**
   * El bot no pisa lo que cargó una persona.
   */
  origen?: ('scraper' | 'manual') | null;
  claveExterna?: string | null;
  huella?: string | null;
  /**
   * La última corrida en que esta promoción seguía publicada en el origen.
   */
  vistoPorUltimaVez?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Las marcas cuyas promociones se publican, y de donde las lee el bot.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plataformas".
 */
export interface Plataforma {
  id: number;
  nombre: string;
  /**
   * Se genera solo si lo dejas vacío. Una vez publicado, cambiarlo pide cargar un 301.
   */
  slug?: string | null;
  /**
   * Se muestra en las tarjetas de promocion.
   */
  logo?: (number | null) | Media;
  /**
   * La home de la marca. No es de donde se scrapea.
   */
  urlSitio?: string | null;
  /**
   * La URL exacta que visita el bot. Si la plataforma rediseña y la mueve, se corrige acá.
   */
  urlPromociones: string;
  /**
   * De acá cuelga /bonus-engine/api/campaigns. Es el PROXY_URL que declara el sitio, y no siempre coincide con el subdominio.
   */
  urlApi?: string | null;
  /**
   * Con qué código se lee esta página. Cada plataforma maqueta distinto, así que casi siempre tiene el suyo.
   */
  adaptador: 'jugadon' | 'jugadon-bonus-engine' | 'jugadon-sircms';
  /**
   * Destildar para que el bot la saltee. Las promociones ya publicadas siguen online: esto solo frena la lectura.
   */
  scrapeoActivo?: boolean | null;
  /**
   * La escribe el bot. Si quedó vieja, algo dejó de correr.
   */
  ultimaCorrida?: string | null;
  /**
   * Qué encontró el bot la última vez, o por qué falló.
   */
  ultimoResultado?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Las piezas de campaña que encabezan la pantalla de promociones. Se turnan solas, en el orden de acá abajo.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "banners".
 */
export interface Banner {
  id: number;
  /**
   * Solo para reconocerlo acá adentro. No se muestra en el sitio.
   */
  nombre: string;
  /**
   * La oferta escrita en texto, tal como se lee en la imagen. Ej: "Bono de bienvenida: creá tu cuenta y recibí $25.000".
   */
  mensaje: string;
  /**
   * Faja apaisada. La medida del arte actual es 1350 × 260.
   */
  imagenEscritorio: number | Media;
  /**
   * La misma campaña recompuesta en vertical. La medida actual es 800 × 400.
   */
  imagenTelefono: number | Media;
  /**
   * En qué jurisdicciones se muestra. Vacío es en todas. Si una necesita otro arte, cargá la pieza aparte y sacá esa jurisdicción de esta lista: si no, se ven las dos.
   */
  plataformas?: (number | Plataforma)[] | null;
  /**
   * Las promociones que este banner ya está mostrando. No aparecen en la grilla de abajo, para no repetirlas.
   */
  promocionesQueCubre?: (number | Promocion)[] | null;
  /**
   * De menor a mayor. El más chico se muestra primero.
   */
  orden: number;
  /**
   * Destildado, el banner deja de salir en el sitio pero no se borra.
   */
  activo?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Las salas, agencias y puntos de pago que se muestran en el mapa del sitio. Cada uno necesita su par de coordenadas para aparecer.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "puntos-de-venta".
 */
export interface PuntoDeVenta {
  id: number;
  /**
   * Como se anuncia el local. Es lo que encabeza la ficha en el mapa.
   */
  nombre: string;
  /**
   * La sala es el local propio; la agencia, el comercio adherido de la red de Jugadon; el punto de pago, el comercio donde solo se carga y se retira, sin juego. Decide el color del marcador y es uno de los dos filtros del mapa.
   */
  tipo: 'sala' | 'agencia' | 'punto-de-pago';
  /**
   * Calle y número, como para llegar. Sin la localidad ni la provincia.
   */
  direccion: string;
  localidad: string;
  /**
   * Agrupa los puntos en el filtro del mapa.
   */
  provincia:
    | 'buenos-aires'
    | 'caba'
    | 'catamarca'
    | 'chaco'
    | 'chubut'
    | 'cordoba'
    | 'corrientes'
    | 'entre-rios'
    | 'formosa'
    | 'jujuy'
    | 'la-pampa'
    | 'la-rioja'
    | 'mendoza'
    | 'misiones'
    | 'neuquen'
    | 'rio-negro'
    | 'salta'
    | 'san-juan'
    | 'san-luis'
    | 'santa-cruz'
    | 'santa-fe'
    | 'santiago-del-estero'
    | 'tierra-del-fuego'
    | 'tucuman';
  /**
   * En Argentina es un número negativo: -33.30…
   */
  latitud: number;
  /**
   * También negativo: -66.33…
   */
  longitud: number;
  /**
   * Opcional. Si se carga, en el celular sale como enlace para llamar.
   */
  telefono?: string | null;
  /**
   * Una línea por tramo. Por ejemplo: "Lunes a viernes de 10 a 22".
   */
  horarios?: string | null;
  /**
   * Opcional. La fachada, para reconocer el local al llegar.
   */
  foto?: (number | null) | Media;
  /**
   * Lo pone la importación. Es lo que permite volver a importar la planilla sin duplicar el local.
   */
  codigoExterno?: string | null;
  /**
   * Destildar para sacarlo del mapa sin borrarlo: sirve para un local cerrado por refacción.
   */
  activo?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Cuando una entrada cambia de URL, registra aquí el 301 de la dirección vieja a la nueva.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?: {
      relationTo: 'posts';
      value: number | Post;
    } | null;
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Se mantiene solo: cada vez que se crea o edita una entrada, su fila se actualiza. No se edita a mano.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: number;
  title?: string | null;
  priority?: number | null;
  doc: {
    relationTo: 'posts';
    value: number | Post;
  };
  resumen?: string | null;
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'scrapearPromociones';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'scrapearPromociones') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'authors';
        value: number | Author;
      } | null)
    | ({
        relationTo: 'promociones';
        value: number | Promocion;
      } | null)
    | ({
        relationTo: 'plataformas';
        value: number | Plataforma;
      } | null)
    | ({
        relationTo: 'banners';
        value: number | Banner;
      } | null)
    | ({
        relationTo: 'puntos-de-venta';
        value: number | PuntoDeVenta;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'search';
        value: number | Search;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: number | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  titulo?: T;
  slug?: T;
  resumen?: T;
  portada?: T;
  contenido?: T;
  categoria?: T;
  etiquetas?: T;
  autor?: T;
  publicadoEn?: T;
  actualizadoEn?: T;
  destacado?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  nombre?: T;
  slug?: T;
  descripcion?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  nombre?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  nombre?: T;
  slug?: T;
  cargo?: T;
  bio?: T;
  foto?: T;
  credenciales?:
    | T
    | {
        texto?: T;
        id?: T;
      };
  enlaces?:
    | T
    | {
        etiqueta?: T;
        url?: T;
        id?: T;
      };
  usuario?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promociones_select".
 */
export interface PromocionesSelect<T extends boolean = true> {
  plataforma?: T;
  titulo?: T;
  slug?: T;
  tipo?: T;
  oferta?: T;
  resumen?: T;
  portada?: T;
  imagenOrigen?: T;
  rollover?: T;
  depositoMinimo?: T;
  topeDeConversion?: T;
  cuotaMinima?: T;
  diasParaCumplir?: T;
  usosPorUsuario?: T;
  combinable?: T;
  activacion?: T;
  codigo?: T;
  verticales?: T;
  juegosHabilitados?: T;
  puntosClave?: T;
  urlDestino?: T;
  vigenciaDesde?: T;
  vigenciaHasta?: T;
  estado?: T;
  destacada?: T;
  origen?: T;
  claveExterna?: T;
  huella?: T;
  vistoPorUltimaVez?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plataformas_select".
 */
export interface PlataformasSelect<T extends boolean = true> {
  nombre?: T;
  slug?: T;
  logo?: T;
  urlSitio?: T;
  urlPromociones?: T;
  urlApi?: T;
  adaptador?: T;
  scrapeoActivo?: T;
  ultimaCorrida?: T;
  ultimoResultado?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "banners_select".
 */
export interface BannersSelect<T extends boolean = true> {
  nombre?: T;
  mensaje?: T;
  imagenEscritorio?: T;
  imagenTelefono?: T;
  plataformas?: T;
  promocionesQueCubre?: T;
  orden?: T;
  activo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "puntos-de-venta_select".
 */
export interface PuntosDeVentaSelect<T extends boolean = true> {
  nombre?: T;
  tipo?: T;
  direccion?: T;
  localidad?: T;
  provincia?: T;
  latitud?: T;
  longitud?: T;
  telefono?: T;
  horarios?: T;
  foto?: T;
  codigoExterno?: T;
  activo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  epigrafe?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  nombre?: T;
  rol?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  resumen?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  meta?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats".
 */
export interface PayloadJobsStat {
  id: number;
  stats?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats_select".
 */
export interface PayloadJobsStatsSelect<T extends boolean = true> {
  stats?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskScrapearPromociones".
 */
export interface TaskScrapearPromociones {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}